

image:https://img.shields.io/badge/code%20style-black-000000.svg[link="https://github.com/psf/black"]
image:https://img.shields.io/badge/License-MIT-yellow.svg[link="https://opensource.org/licenses/MIT"]
image:https://img.shields.io/twitter/url/https/twitter.com/fold_left.svg?style=social&label=Follow%20%40zhinst[link="https://twitter.com/zhinst"]


= Zurich Instruments LabOne API Examples

The `LabOne API examples` are a collection of various examples for the different APIs that LabOne supports.
Right now only examples for the python api are inside this project.
Other will follow soon.
In the mean time all examples not in this project are documented in the https://docs.zhinst.com/labone_api/index.html[LabOne API documentation].

== Project structure

----
📒 repository
  📂 common <1>
    📂 <api> <3>
      📄 example_*
  📂 <instrument> <2>
    📂 <api> <3>
      📄 example_*
  📂 utils <4>
    📂 <api> <3>
----
<1> The `common` directory contains examples valid for all instruments.
<2> Instrument specific examples are located in the respective directory
<3> Each directory is separated into the different APIs (e.g. python)
<4> General helper functions are located in the `utils` directory

== Python API

In order to run the python examples you need to have the latest https://pypi.org/project/zhinst/[`zhinst`] package installed and https://www.zhinst.com/others/instruments/labone/labone-all-in-one[LabOne] up and running. (please refer to the https://docs.zhinst.com/labone_programming_manual/overview.html[LabOne user manual] for further information)

The python examples are designed in a way that they can be run from the command line. 

....
$ python path/to/example.py --help
....

Each example has a run_example function that contains the example source.
Feel free to experiment, change or copy parts of the examples.